# Generated by Django 4.2.5 on 2023-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_do_protocolo', models.CharField(max_length=100)),
                ('apresentante', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
    ]
